import StyledJsxRegistry from "./registry";

export const metadata = {
  title: "Dom Hub",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-br">
      <link
        href="https://fonts.googleapis.com/css2?family=Montserrat:wght@600;700&family=Work+Sans:wght@400;500;600&display=swap"
        rel="stylesheet"
      />
      <StyledJsxRegistry>{children}</StyledJsxRegistry>
    </html>
  );
}
